"""Add sender_username to Transaction model

Revision ID: 6584a3854df5
Revises: c337c8d72cac
Create Date: 2024-12-09 15:14:43.209207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6584a3854df5'
down_revision = 'c337c8d72cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_username', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('sender_username')

    # ### end Alembic commands ###
